### ISSUE TITLE
Not translate properly every request.  Maximum time its showing this error

### ISSUE THREAD

**Issue by saifulbabo67646** [k3rn31p4nic/google-translate-api#6]
{HTTPError
 at translate (/rbd/pnpm-volume/d3e2a241-36ab-414f-9781-4e47668ac65e/node_modules/.registry.npmjs.org/@k3rn31p4nic/google-translate-api/1.0.5/node_modules/@k3rn31p4nic/google-translate-api/src/index.js:143:19)

    at process._tickCallback (internal/process/next_tick.js:68:7)

  name: 'HTTPError',

  statusCode: 403,

  statusMessage: 'Forbidden' }

**Comment by k3rn31p4nic** [comment]
Can you give any context? And can you give a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of how you're using it?
